# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addsubject.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sleet_database

class Ui_addsubject(object):

    def open_add(self):
        from add import Ui_add
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_add()
        self.ui.setupUi(self.window)
        self.window.show()

    def get_details(self):

        subject = self.textEdit_2.toPlainText()
        subject = subject.lower()
        link = self.textEdit_4.toPlainText()
        sleet_database.insertinto_subject_list(subject,link)
        self.textEdit_2.setText("")
        self.textEdit_4.setText("")


    def setupUi(self, addsubject):
        addsubject.setObjectName("addsubject")
        addsubject.resize(700, 500)
        addsubject.setMinimumSize(QtCore.QSize(700, 500))
        addsubject.setMaximumSize(QtCore.QSize(700, 500))
        addsubject.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.0356633 rgba(107, 107, 107, 255), stop:1 rgba(51, 51, 51, 255));")
        self.centralwidget = QtWidgets.QWidget(addsubject)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setEnabled(True)
        self.textEdit_2.setGeometry(QtCore.QRect(170, 140, 351, 44))
        self.textEdit_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50, 50, 50, 255));\n"
"border-radius : 20px;\n"
" \n"
"color: rgb(255, 255, 255);\n"
"font-size:20px;\n"
"padding-left:30px;\n"
"padding-top : 5px;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setAcceptRichText(False)

        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setEnabled(True)
        self.textEdit_4.setGeometry(QtCore.QRect(170, 220, 351, 44))
        self.textEdit_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50, 50, 50, 255));\n"
"border-radius : 20px;\n"
" \n"
"color: rgb(255, 255, 255);\n"
"font-size:20px;\n"
"padding-left:30px;\n"
"padding-top : 5px;")
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_4.setAcceptRichText(False)

        self.instructionbtn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.instructionbtn_2.setGeometry(QtCore.QRect(250, 310, 191, 41))
        self.instructionbtn_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(115, 129, 241);\n"
"border-color: grey;\n"
"border-radius:10px ;\n"
"border-width:2px;\n"
"border-style:solid;\n"
"font-weight: bold;\n"
"transition: all 0.5s;\n"
"font-size:13px;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"background-color:rgb(83, 83, 83);\n"
"border-color: black;\n"
"border-width:5px\n"
"\n"
"    \n"
"}\n"
"\n"
"\n"
"")
        self.instructionbtn_2.setObjectName("instructionbtn_2")

        self.instructionbtn_2.clicked.connect(self.get_details)

        self.instructionbtn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.instructionbtn_6.setGeometry(QtCore.QRect(590, 450, 91, 31))
        self.instructionbtn_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(115, 129, 241);\n"
"border-color: grey;\n"
"border-radius:10px ;\n"
"border-width:2px;\n"
"border-style:solid;\n"
"font-weight: bold;\n"
"transition: all 0.5s;\n"
"font-size:13px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(83, 83, 83);\n"
"border-color: black;\n"
"border-width:5px\n"
"\n"
"    \n"
"}\n"
"\n"
"\n"
"")
        self.instructionbtn_6.setObjectName("instructionbtn_6")

        self.instructionbtn_6.clicked.connect(self.open_add)
        self.instructionbtn_6.clicked.connect(addsubject.close)

        addsubject.setCentralWidget(self.centralwidget)

        self.retranslateUi(addsubject)
        QtCore.QMetaObject.connectSlotsByName(addsubject)

    def retranslateUi(self, addsubject):
        _translate = QtCore.QCoreApplication.translate
        addsubject.setWindowTitle(_translate("addsubject", "Sleet"))
        self.textEdit_2.setPlaceholderText(_translate("addsubject", "Subject"))
        self.textEdit_4.setPlaceholderText(_translate("addsubject", "Link (eg: https://meet-link.com )"))
        self.instructionbtn_2.setText(_translate("addsubject", "Submit"))
        self.instructionbtn_6.setText(_translate("addsubject", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addsubject = QtWidgets.QMainWindow()
    ui = Ui_addsubject()
    ui.setupUi(addsubject)
    addsubject.show()
    sys.exit(app.exec_())
