# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deletetimetable.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sleet_database

class Ui_delete_day(object):

    def get_details(self):
        day = self.textEdit_2.toPlainText()
        day = day.lower()
        day = day[:3]
        sleet_database.delete_timetable(day)
        self.textEdit_2.setText("")


    def open_delete(self):
        from delete import Ui_delete_2
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_delete_2()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, delete_day):
        delete_day.setObjectName("delete_day")
        delete_day.resize(500, 500)
        delete_day.setMinimumSize(QtCore.QSize(500, 500))
        delete_day.setMaximumSize(QtCore.QSize(500, 500))
        delete_day.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.0356633 rgba(107, 107, 107, 255), stop:1 rgba(51, 51, 51, 255));")
        self.centralwidget = QtWidgets.QWidget(delete_day)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setEnabled(True)
        self.textEdit_2.setGeometry(QtCore.QRect(120, 150, 281, 44))
        self.textEdit_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50, 50, 50, 255));\n"
"border-radius : 20px;\n"
" \n"
"color: rgb(255, 255, 255);\n"
"font-size:20px;\n"
"padding-left:30px;\n"
"padding-top : 5px;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setAcceptRichText(False)

        self.instructionbtn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.instructionbtn_6.setGeometry(QtCore.QRect(390, 450, 91, 31))
        self.instructionbtn_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(115, 129, 241);\n"
"border-color: grey;\n"
"border-radius:10px ;\n"
"border-width:2px;\n"
"border-style:solid;\n"
"font-weight: bold;\n"
"transition: all 0.5s;\n"
"font-size:13px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(83, 83, 83);\n"
"border-color: black;\n"
"border-width:5px\n"
"\n"
"    \n"
"}\n"
"\n"
"\n"
"")
        self.instructionbtn_6.setObjectName("instructionbtn_6")

        self.instructionbtn_6.clicked.connect(self.open_delete)
        self.instructionbtn_6.clicked.connect(delete_day.close)

        self.instructionbtn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.instructionbtn_2.setGeometry(QtCore.QRect(160, 230, 201, 41))
        self.instructionbtn_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(115, 129, 241);\n"
"border-color: grey;\n"
"border-radius:10px ;\n"
"border-width:2px;\n"
"border-style:solid;\n"
"font-weight: bold;\n"
"transition: all 0.5s;\n"
"font-size:13px;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"background-color:rgb(83, 83, 83);\n"
"border-color: black;\n"
"border-width:5px\n"
"\n"
"    \n"
"}\n"
"\n"
"\n"
"")
        self.instructionbtn_2.setObjectName("instructionbtn_2")

        self.instructionbtn_2.clicked.connect(self.get_details)

        delete_day.setCentralWidget(self.centralwidget)

        self.retranslateUi(delete_day)
        QtCore.QMetaObject.connectSlotsByName(delete_day)

    def retranslateUi(self, delete_day):
        _translate = QtCore.QCoreApplication.translate
        delete_day.setWindowTitle(_translate("delete_day", "Sleet"))
        self.textEdit_2.setPlaceholderText(_translate("delete_day", "Day (eg: Mon or Monday)"))
        self.instructionbtn_6.setText(_translate("delete_day", "Back"))
        self.instructionbtn_2.setText(_translate("delete_day", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    delete_day = QtWidgets.QMainWindow()
    ui = Ui_delete_day()
    ui.setupUi(delete_day)
    delete_day.show()
    sys.exit(app.exec_())
