# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'disclaimer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_disclaimer(object):
    def setupUi(self, disclaimer):
        disclaimer.setObjectName("disclaimer")
        disclaimer.resize(600, 400)
        disclaimer.setMinimumSize(QtCore.QSize(600, 400))
        disclaimer.setMaximumSize(QtCore.QSize(600, 400))
        disclaimer.setStyleSheet("background-color: black;\n"
"")
        self.centralwidget = QtWidgets.QWidget(disclaimer)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 71))
        self.label.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(121, 121, 121);\n"
"font-size : 50px;\n"
"\n"
"")
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 641, 31))
        self.label_7.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(255, 0, 0);\n"
"font-size : 15px;\n"
"\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 641, 31))
        self.label_8.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(255, 0, 0);\n"
"font-size : 15px;\n"
"\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 150, 641, 31))
        self.label_9.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(255, 0, 0);\n"
"font-size : 15px;\n"
"\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 180, 641, 31))
        self.label_10.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(255, 0, 0);\n"
"font-size : 15px;\n"
"\n"
"")
        self.label_10.setObjectName("label_10")
        disclaimer.setCentralWidget(self.centralwidget)

        self.retranslateUi(disclaimer)
        QtCore.QMetaObject.connectSlotsByName(disclaimer)

    def retranslateUi(self, disclaimer):
        _translate = QtCore.QCoreApplication.translate
        disclaimer.setWindowTitle(_translate("disclaimer", "Sleet"))
        self.label.setText(_translate("disclaimer", "Sleet"))
        self.label_7.setText(_translate("disclaimer", "Disclaimer : Creator of this script is not responsible for any misuse and the user is "))
        self.label_8.setText(_translate("disclaimer", "using it at his own risk and is responsible for any misuse done."))
        self.label_9.setText(_translate("disclaimer", "Sleet was made as a fun project."))
        self.label_10.setText(_translate("disclaimer", "Do not change the code."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    disclaimer = QtWidgets.QMainWindow()
    ui = Ui_disclaimer()
    ui.setupUi(disclaimer)
    disclaimer.show()
    sys.exit(app.exec_())
