# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display_timetable.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sleet_database

class Ui_time_table(object):

    def get_database_timetable(self):
        st = "Mon"
        if self.radioButton.isChecked():
            st = self.radioButton.text()
        elif self.radioButton_2.isChecked():
            st = self.radioButton_2.text()
        elif self.radioButton_3.isChecked():
            st = self.radioButton_3.text()
        elif self.radioButton_4.isChecked():
            st = self.radioButton_4.text()
        elif self.radioButton_5.isChecked():
            st = self.radioButton_5.text()
        elif self.radioButton_6.isChecked():
            st = self.radioButton_6.text()
        elif self.radioButton_7.isChecked():
            from display_subject import Ui_subject_table
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_subject_table()
            self.ui.setupUi(self.window)
            self.window.show()

        st = st.lower()
        rows = sleet_database.timetable(st[:3])
        self.tableWidget.setRowCount(len(rows))
        for i in range(len(rows)):
            self.tableWidget.setItem(i, 0, QtWidgets.QTableWidgetItem(rows[i][0]))
            self.tableWidget.setItem(i, 1, QtWidgets.QTableWidgetItem(rows[i][1]))
            self.tableWidget.setItem(i, 2, QtWidgets.QTableWidgetItem(rows[i][2]))


    def setupUi(self, time_table):
        time_table.setObjectName("time_table")
        time_table.resize(700, 500)
        time_table.setMinimumSize(QtCore.QSize(700, 500))
        time_table.setMaximumSize(QtCore.QSize(700, 500))
        time_table.setStyleSheet("\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.504049, fy:0.523, stop:0 rgba(109, 108, 104, 255), stop:1 rgba(50, 50, 50, 255));")
        self.tableWidget = QtWidgets.QTableWidget(time_table)
        self.tableWidget.setGeometry(QtCore.QRect(20, 160, 661, 311))
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(99999, 99999))
        self.tableWidget.setStyleSheet("color:black;\n"
"background-color:rgb(99, 99, 99)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.label = QtWidgets.QLabel(time_table)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 71))
        self.label.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: grey;\n"
"font-size : 50px;\n"
"\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(time_table)
        self.label_2.setGeometry(QtCore.QRect(270, 30, 171, 71))
        self.label_2.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color:black;\n"
"font-size : 30px;\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(time_table)
        self.radioButton.setGeometry(QtCore.QRect(30, 100, 81, 21))
        self.radioButton.setStyleSheet("background-color:rgb(86, 86, 86);")
        self.radioButton.setObjectName("radioButton")
        self.radioButton.toggled.connect(self.get_database_timetable)
        self.radioButton_2 = QtWidgets.QRadioButton(time_table)
        self.radioButton_2.setGeometry(QtCore.QRect(140, 100, 81, 21))
        self.radioButton_2.setStyleSheet("background-color:rgb(86, 86, 86);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton.toggled.connect(self.get_database_timetable)
        self.radioButton_3 = QtWidgets.QRadioButton(time_table)
        self.radioButton_3.setGeometry(QtCore.QRect(250, 100, 81, 21))
        self.radioButton_3.setStyleSheet("background-color:rgb(86, 86, 86);")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton.toggled.connect(self.get_database_timetable)
        self.radioButton_4 = QtWidgets.QRadioButton(time_table)
        self.radioButton_4.setGeometry(QtCore.QRect(360, 100, 81, 21))
        self.radioButton_4.setStyleSheet("background-color:rgb(86, 86, 86);")
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton.toggled.connect(self.get_database_timetable)
        self.radioButton_5 = QtWidgets.QRadioButton(time_table)
        self.radioButton_5.setGeometry(QtCore.QRect(470, 100, 81, 21))
        self.radioButton_5.setStyleSheet("background-color:rgb(86, 86, 86);")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton.toggled.connect(self.get_database_timetable)
        self.radioButton_6 = QtWidgets.QRadioButton(time_table)
        self.radioButton_6.setGeometry(QtCore.QRect(580, 100, 81, 21))
        self.radioButton_6.setStyleSheet("background-color:rgb(86, 86, 86);")
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton.toggled.connect(self.get_database_timetable)
        self.radioButton_7 = QtWidgets.QRadioButton(time_table)
        self.radioButton_7.setGeometry(QtCore.QRect(300, 130, 81, 21))
        self.radioButton_7.setStyleSheet("background-color:rgb(86, 86, 86);")
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_7.toggled.connect(self.get_database_timetable)
        self.radioButton_7.toggled.connect(time_table.close)
        self.tableWidget.setColumnWidth(0, 213)
        self.tableWidget.setColumnWidth(1, 213)
        self.tableWidget.setColumnWidth(2, 213)
        self.retranslateUi(time_table)
        QtCore.QMetaObject.connectSlotsByName(time_table)

    def retranslateUi(self, time_table):
        _translate = QtCore.QCoreApplication.translate
        time_table.setWindowTitle(_translate("time_table", "Sleet"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("time_table", "Subject"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("time_table", "Time-Start"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("time_table", "Time-End"))
        self.label.setText(_translate("time_table", "Sleet"))
        self.label_2.setText(_translate("time_table", "Time-Table"))
        self.radioButton.setText(_translate("time_table", "Monday"))
        self.radioButton_2.setText(_translate("time_table", "Tuesday"))
        self.radioButton_3.setText(_translate("time_table", "Wednesday"))
        self.radioButton_4.setText(_translate("time_table", "Thursday"))
        self.radioButton_5.setText(_translate("time_table", "Friday"))
        self.radioButton_6.setText(_translate("time_table", "Saturday"))
        self.radioButton_7.setText(_translate("time_table", "Subject"))
        self.get_database_timetable()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    time_table = QtWidgets.QDialog()
    ui = Ui_time_table()
    ui.setupUi(time_table)
    time_table.show()
    sys.exit(app.exec_())
