# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display_subject.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sleet_database

class Ui_subject_table(object):

    def get_database_subject(self):
        rows = sleet_database.subject_list()
        self.tableWidget.setRowCount(len(rows))
        for i in range(len(rows)):
            self.tableWidget.setItem(i, 0, QtWidgets.QTableWidgetItem(rows[i][0]))
            self.tableWidget.setItem(i, 1, QtWidgets.QTableWidgetItem(rows[i][1]))


    def setupUi(self, subject_table):
        subject_table.setObjectName("subject_table")
        subject_table.resize(700, 500)
        subject_table.setMinimumSize(QtCore.QSize(700, 500))
        subject_table.setMaximumSize(QtCore.QSize(700, 500))
        subject_table.setStyleSheet("\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.504049, fy:0.523, stop:0 rgba(109, 108, 104, 255), stop:1 rgba(50, 50, 50, 255));")
        self.tableWidget = QtWidgets.QTableWidget(subject_table)
        self.tableWidget.setGeometry(QtCore.QRect(30, 160, 641, 311))
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(99999, 99999))
        self.tableWidget.setStyleSheet("color:black;\n"
"background-color:rgb(99, 99, 99)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnWidth(1,435)
        self.tableWidget.setColumnWidth(0, 200)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.label = QtWidgets.QLabel(subject_table)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 71))
        self.label.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: grey;\n"
"font-size : 50px;\n"
"\n"
"")
        self.label.setObjectName("label")

        self.retranslateUi(subject_table)
        QtCore.QMetaObject.connectSlotsByName(subject_table)


    def retranslateUi(self, subject_table):
        _translate = QtCore.QCoreApplication.translate
        subject_table.setWindowTitle(_translate("subject_table", "Sleet"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("subject_table", "Subject"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("subject_table", "Link"))
        self.label.setText(_translate("subject_table", "Sleet"))
        self.get_database_subject()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    subject_table = QtWidgets.QDialog()
    ui = Ui_subject_table()
    ui.setupUi(subject_table)
    subject_table.show()
    sys.exit(app.exec_())
