# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instruction.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_instruction(object):
    def setupUi(self, instruction):
        instruction.setObjectName("instruction")
        instruction.resize(678, 493)
        instruction.setStyleSheet("background-color: black;")
        self.centralwidget = QtWidgets.QWidget(instruction)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 111, 71))
        self.label.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(121, 121, 121);\n"
"font-size : 50px;\n"
"\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 50, 201, 31))
        self.label_2.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(121, 121, 121);\n"
"font-size : 20px;\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 531, 31))
        self.label_3.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(35, 255, 1);\n"
"font-size : 15px;\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 641, 31))
        self.label_4.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(35, 255, 1);\n"
"font-size : 15px;\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 641, 31))
        self.label_5.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(35, 255, 1);\n"
"font-size : 15px;\n"
"\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 641, 31))
        self.label_6.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(35, 255, 1);\n"
"font-size : 15px;\n"
"\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 641, 31))
        self.label_7.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(35, 255, 1);\n"
"font-size : 15px;\n"
"\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 240, 641, 31))
        self.label_8.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(35, 255, 1);\n"
"font-size : 15px;\n"
"\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 270, 641, 31))
        self.label_9.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(35, 255, 1);\n"
"font-size : 15px;\n"
"\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 300, 641, 31))
        self.label_10.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(35, 255, 1);\n"
"font-size : 15px;\n"
"\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 330, 641, 31))
        self.label_11.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(35, 255, 1);\n"
"font-size : 15px;\n"
"\n"
"")
        self.label_11.setObjectName("label_11")
        instruction.setCentralWidget(self.centralwidget)

        self.retranslateUi(instruction)
        QtCore.QMetaObject.connectSlotsByName(instruction)

    def retranslateUi(self, instruction):
        _translate = QtCore.QCoreApplication.translate
        instruction.setWindowTitle(_translate("instruction", "Sleet"))
        self.label.setText(_translate("instruction", "Sleet"))
        self.label_2.setText(_translate("instruction", "by Tarun Nair"))
        self.label_3.setText(_translate("instruction", "Hello this is Sleet, Sleet allows a user to manage their video conference or meet."))
        self.label_4.setText(_translate("instruction", "Sleet currently supports only google-meet, there are two versions of sleet (command-line and UI)."))
        self.label_5.setText(_translate("instruction", "This is version 1.1 of Sleet"))
        self.label_6.setText(_translate("instruction", "Many websites do not allow Sleet, worry not *winks in binary* I got a fix."))
        self.label_7.setText(_translate("instruction", "Sleet currently supports only google-meet, there are two versions of sleet (command-line and UI)."))
        self.label_8.setText(_translate("instruction", "Ensure to type in correct details otherwise the bot won\'t run and might fail and do something bad"))
        self.label_9.setText(_translate("instruction", "he\'s a bit dumb or she, I don\'t know we don\'t discriminate."))
        self.label_10.setText(_translate("instruction", "Don\'t worry sleet does not save your details, your credentials will be erased after you close the"))
        self.label_11.setText(_translate("instruction", "application."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    instruction = QtWidgets.QMainWindow()
    ui = Ui_instruction()
    ui.setupUi(instruction)
    instruction.show()
    sys.exit(app.exec_())
