# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sleet.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sleet(object):
    def setupUi(self, sleet):
        sleet.setObjectName("sleet")
        sleet.resize(400, 300)
        sleet.setMinimumSize(QtCore.QSize(400, 300))
        sleet.setMaximumSize(QtCore.QSize(400, 300))
        sleet.setStyleSheet("background-color:rgb(0, 0, 57);")
        self.centralwidget = QtWidgets.QWidget(sleet)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 111, 71))
        self.label.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(121, 121, 121);\n"
"font-size : 50px;\n"
"\n"
"")
        self.label.setObjectName("label")
        self.instructionbtn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.instructionbtn_2.setGeometry(QtCore.QRect(140, 190, 121, 41))
        self.instructionbtn_2.setStyleSheet("QPushButton{\n"
"background-color:rgb(39, 104, 255);\n"
"border-color: grey;\n"
"border-radius:10px ;\n"
"border-width:2px;\n"
"border-style:solid;\n"
"font-weight: bold;\n"
"transition: all 0.5s;\n"
"font-size:13px;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"background-color:rgb(64, 255, 140);\n"
"border-color: white;\n"
"border-width:5px\n"
"\n"
"    \n"
"}\n"
"\n"
"\n"
"")
        self.instructionbtn_2.setObjectName("instructionbtn_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(80, 120, 249, 44))
        self.textEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(50, 50, 50, 255));\n"
"border-radius : 20px;\n"
" \n"
"color: rgb(255, 255, 255);\n"
"font-size:20px;\n"
"padding-left:30px;\n"
"padding-top : 5px;")
        self.textEdit.setObjectName("textEdit")
        self.instructionbtn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.instructionbtn_6.setGeometry(QtCore.QRect(290, 250, 91, 31))
        self.instructionbtn_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(115, 129, 241);\n"
"border-color: grey;\n"
"border-radius:10px ;\n"
"border-width:2px;\n"
"border-style:solid;\n"
"font-weight: bold;\n"
"transition: all 0.5s;\n"
"font-size:13px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(83, 83, 83);\n"
"border-color: black;\n"
"border-width:5px\n"
"\n"
"    \n"
"}\n"
"\n"
"\n"
"")
        self.instructionbtn_6.setObjectName("instructionbtn_6")
        sleet.setCentralWidget(self.centralwidget)

        self.retranslateUi(sleet)
        QtCore.QMetaObject.connectSlotsByName(sleet)

    def retranslateUi(self, sleet):
        _translate = QtCore.QCoreApplication.translate
        sleet.setWindowTitle(_translate("sleet", "Sleet"))
        self.label.setText(_translate("sleet", "Sleet"))
        self.instructionbtn_2.setText(_translate("sleet", "Start"))
        self.textEdit.setPlaceholderText(_translate("sleet", "Day/Custom"))
        self.instructionbtn_6.setText(_translate("sleet", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sleet = QtWidgets.QMainWindow()
    ui = Ui_sleet()
    ui.setupUi(sleet)
    sleet.show()
    sys.exit(app.exec_())
