# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#from function import Ui_funtion
from instruction import Ui_instruction
from disclaimer import Ui_disclaimer

class Ui_start(object):

#  To open disclaimer
    def open_disclaimer(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_disclaimer()
        self.ui.setupUi(self.window)
        self.window.show()

#  To open instruction
    def open_instruction(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_instruction()
        self.ui.setupUi(self.window)
        self.window.show()

#  To open function
    def open_function(self):
        from function import Ui_funtion
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_funtion()
        self.ui.setupUi(self.window)
        self.window.show()


    def setupUi(self, start):
        start.setObjectName("start")
        start.setEnabled(True)
        start.resize(500, 500)
        start.setMinimumSize(QtCore.QSize(500, 500))
        start.setMaximumSize(QtCore.QSize(500, 500))
        start.setWindowOpacity(1.0)
        start.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.336049 rgba(49, 49, 49, 255), stop:0.686354 rgba(117, 117, 117, 255));")
        start.setIconSize(QtCore.QSize(0, 0))
        start.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(start)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 500))
        self.centralwidget.setMaximumSize(QtCore.QSize(500, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 111, 71))
        self.label.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(121, 121, 121);\n"
"font-size : 50px;\n"
"\n"
"")
        self.label.setObjectName("label")
        self.instructionbtn = QtWidgets.QPushButton(self.centralwidget)
        self.instructionbtn.setGeometry(QtCore.QRect(360, 430, 111, 41))
        self.instructionbtn.setStyleSheet("QPushButton{border-color: grey;\n"
"border-radius:20px ;\n"
"border-width:2px;\n"
"border-style:solid;\n"
"font-weight: bold;\n"
"\n"
"background-color:rgb(80, 112, 109);\n"
"transition: all 0.5s;\n"
"font-size:13px;\n"
"}\n"
"QPushButton:hover{\n"
"border-color: black;\n"
"border-width:5px\n"
"    \n"
"}\n"
"\n"
"\n"
"")
        self.instructionbtn.setObjectName("instructionbtn")

        self.instructionbtn.clicked.connect(self.open_instruction)

        self.loginbtn = QtWidgets.QPushButton(self.centralwidget)
        self.loginbtn.setGeometry(QtCore.QRect(190, 230, 131, 51))
        self.loginbtn.setStyleSheet("QPushButton{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(137, 172, 118, 255));\n"
"border-radius:25px;\n"
"border-width:5px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:solid;}\n"
"QPushButton:hover{\n"
"\n"
"  background-color: #766980; \n"
"  border-color:black;\n"
"border-style:solid;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.loginbtn.setText("")
        self.loginbtn.setObjectName("loginbtn")

        self.loginbtn.clicked.connect(self.open_function)
        self.loginbtn.clicked.connect(start.close)

        self.instructionbtn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.instructionbtn_2.setGeometry(QtCore.QRect(20, 430, 111, 41))
        self.instructionbtn_2.setStyleSheet("QPushButton{border-color: grey;\n"
"border-radius:20px ;\n"
"border-width:2px;\n"
"border-style:solid;\n"
"font-weight: bold;\n"
"\n"
"background-color:rgb(80, 112, 109);\n"
"transition: all 0.5s;\n"
"font-size:13px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(158,26,26,255);\n"
"border-color: black;\n"
"border-width:5px\n"
"\n"
"    \n"
"}\n"
"\n"
"\n"
"")
        self.instructionbtn_2.setObjectName("instructionbtn_2")

        self.instructionbtn_2.clicked.connect(self.open_disclaimer)

        start.setCentralWidget(self.centralwidget)

        self.retranslateUi(start)
        QtCore.QMetaObject.connectSlotsByName(start)

    def retranslateUi(self, start):
        _translate = QtCore.QCoreApplication.translate
        start.setWindowTitle(_translate("start", "Sleet"))
        self.label.setText(_translate("start", "Sleet"))
        self.instructionbtn.setText(_translate("start", "Instruction"))
        self.instructionbtn_2.setText(_translate("start", "Disclaimer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    start = QtWidgets.QMainWindow()
    ui = Ui_start()
    ui.setupUi(start)
    start.show()
    sys.exit(app.exec_())
